<?php
/**
 * CallForwardSettingDetailedCollectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * CallForwardSettingDetailedCollectionTest Class Doc Comment
 *
 * @category    Class
 * @description CallForwardSettingDetailedCollection
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CallForwardSettingDetailedCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CallForwardSettingDetailedCollection"
     */
    public function testCallForwardSettingDetailedCollection()
    {
    }

    /**
     * Test attribute "call_type_filter"
     */
    public function testPropertyCallTypeFilter()
    {
    }

    /**
     * Test attribute "call_forward_type"
     */
    public function testPropertyCallForwardType()
    {
    }

    /**
     * Test attribute "target_type"
     */
    public function testPropertyTargetType()
    {
    }

    /**
     * Test attribute "number_value"
     */
    public function testPropertyNumberValue()
    {
    }

    /**
     * Test attribute "no_answer_timeout"
     */
    public function testPropertyNoAnswerTimeout()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "enabled"
     */
    public function testPropertyEnabled()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "extension"
     */
    public function testPropertyExtension()
    {
    }

    /**
     * Test attribute "voice_mail_user"
     */
    public function testPropertyVoiceMailUser()
    {
    }

    /**
     * Test attribute "number_country"
     */
    public function testPropertyNumberCountry()
    {
    }
}
