<?php
/**
 * ExtensionCollectionTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * ExtensionCollectionTest Class Doc Comment
 *
 * @category    Class
 * @description ExtensionCollection
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExtensionCollectionTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExtensionCollection"
     */
    public function testExtensionCollection()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
    }

    /**
     * Test attribute "route_type"
     */
    public function testPropertyRouteType()
    {
    }

    /**
     * Test attribute "number_value"
     */
    public function testPropertyNumberValue()
    {
    }

    /**
     * Test attribute "friend_value"
     */
    public function testPropertyFriendValue()
    {
    }

    /**
     * Test attribute "ivr"
     */
    public function testPropertyIvr()
    {
    }

    /**
     * Test attribute "hunt_group"
     */
    public function testPropertyHuntGroup()
    {
    }

    /**
     * Test attribute "conference_room"
     */
    public function testPropertyConferenceRoom()
    {
    }

    /**
     * Test attribute "user"
     */
    public function testPropertyUser()
    {
    }

    /**
     * Test attribute "queue"
     */
    public function testPropertyQueue()
    {
    }

    /**
     * Test attribute "conditional_route"
     */
    public function testPropertyConditionalRoute()
    {
    }

    /**
     * Test attribute "number_country"
     */
    public function testPropertyNumberCountry()
    {
    }
}
