<?php
/**
 * FriendDetailedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * FriendDetailedTest Class Doc Comment
 *
 * @category    Class
 * @description FriendDetailed
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FriendDetailedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FriendDetailed"
     */
    public function testFriendDetailed()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "transport"
     */
    public function testPropertyTransport()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "port"
     */
    public function testPropertyPort()
    {
    }

    /**
     * Test attribute "password"
     */
    public function testPropertyPassword()
    {
    }

    /**
     * Test attribute "priority"
     */
    public function testPropertyPriority()
    {
    }

    /**
     * Test attribute "allow"
     */
    public function testPropertyAllow()
    {
    }

    /**
     * Test attribute "from_user"
     */
    public function testPropertyFromUser()
    {
    }

    /**
     * Test attribute "from_domain"
     */
    public function testPropertyFromDomain()
    {
    }

    /**
     * Test attribute "direct_connectivity"
     */
    public function testPropertyDirectConnectivity()
    {
    }

    /**
     * Test attribute "ddi_in"
     */
    public function testPropertyDdiIn()
    {
    }

    /**
     * Test attribute "t38_passthrough"
     */
    public function testPropertyT38Passthrough()
    {
    }

    /**
     * Test attribute "always_apply_transformations"
     */
    public function testPropertyAlwaysApplyTransformations()
    {
    }

    /**
     * Test attribute "rtp_encryption"
     */
    public function testPropertyRtpEncryption()
    {
    }

    /**
     * Test attribute "multi_contact"
     */
    public function testPropertyMultiContact()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "transformation_rule_set"
     */
    public function testPropertyTransformationRuleSet()
    {
    }

    /**
     * Test attribute "call_acl"
     */
    public function testPropertyCallAcl()
    {
    }

    /**
     * Test attribute "outgoing_ddi"
     */
    public function testPropertyOutgoingDdi()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }
}
