<?php
/**
 * IvrDetailedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * IvrDetailedTest Class Doc Comment
 *
 * @category    Class
 * @description IvrDetailed
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class IvrDetailedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "IvrDetailed"
     */
    public function testIvrDetailed()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }

    /**
     * Test attribute "max_digits"
     */
    public function testPropertyMaxDigits()
    {
    }

    /**
     * Test attribute "allow_extensions"
     */
    public function testPropertyAllowExtensions()
    {
    }

    /**
     * Test attribute "no_input_route_type"
     */
    public function testPropertyNoInputRouteType()
    {
    }

    /**
     * Test attribute "no_input_number_value"
     */
    public function testPropertyNoInputNumberValue()
    {
    }

    /**
     * Test attribute "error_route_type"
     */
    public function testPropertyErrorRouteType()
    {
    }

    /**
     * Test attribute "error_number_value"
     */
    public function testPropertyErrorNumberValue()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "welcome_locution"
     */
    public function testPropertyWelcomeLocution()
    {
    }

    /**
     * Test attribute "no_input_locution"
     */
    public function testPropertyNoInputLocution()
    {
    }

    /**
     * Test attribute "error_locution"
     */
    public function testPropertyErrorLocution()
    {
    }

    /**
     * Test attribute "success_locution"
     */
    public function testPropertySuccessLocution()
    {
    }

    /**
     * Test attribute "no_input_extension"
     */
    public function testPropertyNoInputExtension()
    {
    }

    /**
     * Test attribute "error_extension"
     */
    public function testPropertyErrorExtension()
    {
    }

    /**
     * Test attribute "no_input_voice_mail_user"
     */
    public function testPropertyNoInputVoiceMailUser()
    {
    }

    /**
     * Test attribute "error_voice_mail_user"
     */
    public function testPropertyErrorVoiceMailUser()
    {
    }

    /**
     * Test attribute "no_input_number_country"
     */
    public function testPropertyNoInputNumberCountry()
    {
    }

    /**
     * Test attribute "error_number_country"
     */
    public function testPropertyErrorNumberCountry()
    {
    }

    /**
     * Test attribute "excluded_extension_ids"
     */
    public function testPropertyExcludedExtensionIds()
    {
    }
}
