<?php
/**
 * LanguageNameTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * LanguageNameTest Class Doc Comment
 *
 * @category    Class
 * @description LanguageName
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class LanguageNameTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LanguageName"
     */
    public function testLanguageName()
    {
    }

    /**
     * Test attribute "en"
     */
    public function testPropertyEn()
    {
    }

    /**
     * Test attribute "es"
     */
    public function testPropertyEs()
    {
    }

    /**
     * Test attribute "ca"
     */
    public function testPropertyCa()
    {
    }

    /**
     * Test attribute "it"
     */
    public function testPropertyIt()
    {
    }
}
