<?php
/**
 * RecordingDetailedTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * RecordingDetailedTest Class Doc Comment
 *
 * @category    Class
 * @description RecordingDetailed
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RecordingDetailedTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "RecordingDetailed"
     */
    public function testRecordingDetailed()
    {
    }

    /**
     * Test attribute "callid"
     */
    public function testPropertyCallid()
    {
    }

    /**
     * Test attribute "calldate"
     */
    public function testPropertyCalldate()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "duration"
     */
    public function testPropertyDuration()
    {
    }

    /**
     * Test attribute "caller"
     */
    public function testPropertyCaller()
    {
    }

    /**
     * Test attribute "callee"
     */
    public function testPropertyCallee()
    {
    }

    /**
     * Test attribute "recorder"
     */
    public function testPropertyRecorder()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "recorded_file"
     */
    public function testPropertyRecordedFile()
    {
    }
}
