<?php
/**
 * ScheduleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * ScheduleTest Class Doc Comment
 *
 * @category    Class
 * @description Schedule
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ScheduleTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Schedule"
     */
    public function testSchedule()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "time_in"
     */
    public function testPropertyTimeIn()
    {
    }

    /**
     * Test attribute "timeout"
     */
    public function testPropertyTimeout()
    {
    }

    /**
     * Test attribute "monday"
     */
    public function testPropertyMonday()
    {
    }

    /**
     * Test attribute "tuesday"
     */
    public function testPropertyTuesday()
    {
    }

    /**
     * Test attribute "wednesday"
     */
    public function testPropertyWednesday()
    {
    }

    /**
     * Test attribute "thursday"
     */
    public function testPropertyThursday()
    {
    }

    /**
     * Test attribute "friday"
     */
    public function testPropertyFriday()
    {
    }

    /**
     * Test attribute "saturday"
     */
    public function testPropertySaturday()
    {
    }

    /**
     * Test attribute "sunday"
     */
    public function testPropertySunday()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }
}
