<?php
/**
 * UserTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * UserTest Class Doc Comment
 *
 * @category    Class
 * @description User
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "User"
     */
    public function testUser()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "lastname"
     */
    public function testPropertyLastname()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "pass"
     */
    public function testPropertyPass()
    {
    }

    /**
     * Test attribute "do_not_disturb"
     */
    public function testPropertyDoNotDisturb()
    {
    }

    /**
     * Test attribute "is_boss"
     */
    public function testPropertyIsBoss()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "max_calls"
     */
    public function testPropertyMaxCalls()
    {
    }

    /**
     * Test attribute "external_ip_calls"
     */
    public function testPropertyExternalIpCalls()
    {
    }

    /**
     * Test attribute "reject_call_method"
     */
    public function testPropertyRejectCallMethod()
    {
    }

    /**
     * Test attribute "voicemail_enabled"
     */
    public function testPropertyVoicemailEnabled()
    {
    }

    /**
     * Test attribute "voicemail_send_mail"
     */
    public function testPropertyVoicemailSendMail()
    {
    }

    /**
     * Test attribute "voicemail_attach_sound"
     */
    public function testPropertyVoicemailAttachSound()
    {
    }

    /**
     * Test attribute "multi_contact"
     */
    public function testPropertyMultiContact()
    {
    }

    /**
     * Test attribute "gs_qr_code"
     */
    public function testPropertyGsQrCode()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "call_acl"
     */
    public function testPropertyCallAcl()
    {
    }

    /**
     * Test attribute "boss_assistant"
     */
    public function testPropertyBossAssistant()
    {
    }

    /**
     * Test attribute "boss_assistant_white_list"
     */
    public function testPropertyBossAssistantWhiteList()
    {
    }

    /**
     * Test attribute "transformation_rule_set"
     */
    public function testPropertyTransformationRuleSet()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "terminal"
     */
    public function testPropertyTerminal()
    {
    }

    /**
     * Test attribute "extension"
     */
    public function testPropertyExtension()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "outgoing_ddi"
     */
    public function testPropertyOutgoingDdi()
    {
    }

    /**
     * Test attribute "outgoing_ddi_rule"
     */
    public function testPropertyOutgoingDdiRule()
    {
    }

    /**
     * Test attribute "voicemail_locution"
     */
    public function testPropertyVoicemailLocution()
    {
    }

    /**
     * Test attribute "location"
     */
    public function testPropertyLocation()
    {
    }
}
