<?php
/**
 * UserStatusTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ivz\Client;

/**
 * UserStatusTest Class Doc Comment
 *
 * @category    Class
 * @description UserStatus
 * @package     Ivz\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UserStatusTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UserStatus"
     */
    public function testUserStatus()
    {
    }

    /**
     * Test attribute "user_name"
     */
    public function testPropertyUserName()
    {
    }

    /**
     * Test attribute "company_name"
     */
    public function testPropertyCompanyName()
    {
    }

    /**
     * Test attribute "company_domain"
     */
    public function testPropertyCompanyDomain()
    {
    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {
    }

    /**
     * Test attribute "voice_mail"
     */
    public function testPropertyVoiceMail()
    {
    }

    /**
     * Test attribute "gs_qr_code"
     */
    public function testPropertyGsQrCode()
    {
    }

    /**
     * Test attribute "user_agent"
     */
    public function testPropertyUserAgent()
    {
    }

    /**
     * Test attribute "ip_registered"
     */
    public function testPropertyIpRegistered()
    {
    }

    /**
     * Test attribute "status_terminal"
     */
    public function testPropertyStatusTerminal()
    {
    }

    /**
     * Test attribute "terminal_name"
     */
    public function testPropertyTerminalName()
    {
    }

    /**
     * Test attribute "terminal_password"
     */
    public function testPropertyTerminalPassword()
    {
    }

    /**
     * Test attribute "extension_number"
     */
    public function testPropertyExtensionNumber()
    {
    }
}
