<?php
/**
 * AuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ivz\Client;

use \Ivz\Client\Configuration;
use \Ivz\Client\ApiException;
use \Ivz\Client\ObjectSerializer;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuthApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for postAdminAuthenticate
     *
     * Retrieve JWT token.
     *
     */
    public function testPostAdminAuthenticate()
    {
    }

    /**
     * Test case for postAuthTokenExchangeTokenCollection
     *
     * Creates a Token resource..
     *
     */
    public function testPostAuthTokenExchangeTokenCollection()
    {
    }

    /**
     * Test case for postTokenRefresh
     *
     * Retrieve JWT token.
     *
     */
    public function testPostTokenRefresh()
    {
    }

    /**
     * Test case for postUserAuthenticate
     *
     * Retrieve JWT token.
     *
     */
    public function testPostUserAuthenticate()
    {
    }
}
