<?php
/**
 * MyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ivoz Provider
 *
 * Client REST API
 *
 * OpenAPI spec version: 2.20.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.31
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ivz\Client;

use \Ivz\Client\Configuration;
use \Ivz\Client\ApiException;
use \Ivz\Client\ObjectSerializer;

/**
 * MyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ivz\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MyApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getCallStatsItem
     *
     * Retrieves a CallStats resource..
     *
     */
    public function testGetCallStatsItem()
    {
    }

    /**
     * Test case for getMyActiveCallsActiveCallsItem
     *
     * Retrieves a ActiveCalls resource..
     *
     */
    public function testGetMyActiveCallsActiveCallsItem()
    {
    }

    /**
     * Test case for getMyCallForwardSettingsCallForwardSettingCollection
     *
     * Retrieves the collection of CallForwardSetting resources..
     *
     */
    public function testGetMyCallForwardSettingsCallForwardSettingCollection()
    {
    }

    /**
     * Test case for getMyCallHistoryUsersCdrCollection
     *
     * Retrieves the collection of UsersCdr resources..
     *
     */
    public function testGetMyCallHistoryUsersCdrCollection()
    {
    }

    /**
     * Test case for getMyCompanyAssistantsUserCollection
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testGetMyCompanyAssistantsUserCollection()
    {
    }

    /**
     * Test case for getMyCompanyCountryCountryItem
     *
     * Retrieves a Country resource..
     *
     */
    public function testGetMyCompanyCountryCountryItem()
    {
    }

    /**
     * Test case for getMyCompanyExtensionsExtensionCollection
     *
     * Retrieves the collection of Extension resources..
     *
     */
    public function testGetMyCompanyExtensionsExtensionCollection()
    {
    }

    /**
     * Test case for getMyCompanyVoicemailsUserCollection
     *
     * Retrieves the collection of User resources..
     *
     */
    public function testGetMyCompanyVoicemailsUserCollection()
    {
    }

    /**
     * Test case for getMyProfileUserItem
     *
     * Retrieves a User resource..
     *
     */
    public function testGetMyProfileUserItem()
    {
    }

    /**
     * Test case for getMyRegistrationSummaryRegistrationSummaryItem
     *
     * Retrieves a RegistrationSummary resource..
     *
     */
    public function testGetMyRegistrationSummaryRegistrationSummaryItem()
    {
    }

    /**
     * Test case for getUserStatusItem
     *
     * Retrieves a UserStatus resource..
     *
     */
    public function testGetUserStatusItem()
    {
    }

    /**
     * Test case for getWebThemeItem
     *
     * Retrieves a WebTheme resource..
     *
     */
    public function testGetWebThemeItem()
    {
    }

    /**
     * Test case for postMyCallForwardSettingsCallForwardSettingItem
     *
     * Creates a CallForwardSetting resource..
     *
     */
    public function testPostMyCallForwardSettingsCallForwardSettingItem()
    {
    }

    /**
     * Test case for putMyProfileUserItem
     *
     * Replaces the User resource..
     *
     */
    public function testPutMyProfileUserItem()
    {
    }
}
